### ISSUE TITLE
CentOS 7 运行错误

### ISSUE THREAD

**Issue by developerworks** [luxiaok/DNSmasqWeb#1]
```sh
[root@dnsmasqweb DNSmasqWeb]# python run.py
[2015-08-31 02:54:28] Listen On Port 9886
[I 150831 02:55:44 web:1908] 200 GET / (192.168.8.134) 17.25ms
[I 150831 02:55:44 web:1908] 200 GET /xk_static/bootstrap/css/bootstrap.min.css?v=282663d1dc8a60dcef58304c09005aa5 (192.168.8.134) 5.70ms
[I 150831 02:55:44 web:1908] 200 GET /xk_static/css/xk_login.css?v=af6ea01d402621dbec6522f64799b2d6 (192.168.8.134) 1.58ms
[I 150831 02:55:44 web:1908] 200 GET /xk_static/images/login_bg.png (192.168.8.134) 1.67ms
[W 150831 02:55:44 web:1908] 404 GET /favicon.ico (192.168.8.134) 4.27ms
[I 150831 02:55:51 web:1908] 302 POST / (192.168.8.134) 6.19ms
sh: /etc/init.d/dnsmasq: 没有那个文件或目录
[E 150831 02:55:51 web:1496] Uncaught exception GET /dashboard (192.168.8.134)
    HTTPServerRequest(protocol='http', host='192.168.8.88:9886', method='GET', uri='/dashboard', version='HTTP/1.1', remote_ip='192.168.8.134', headers={'Accept-Language': 'en,zh-CN;q=0.8,zh;q=0.6,ja;q=0.4,zh-TW;q=0.2,ko;q=0.2,de;q=0.2,ar;q=0.2,fr;q=0.2', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': '192.168.8.88:9886', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://192.168.8.88:9886/', 'Cache-Control': 'max-age=0', 'Cookie': '_xsrf=2|38998258|ad727c3bd08df0b3d1114f26e517925f|1440989744; xk_auth_token="2|1:0|10:1440989751|13:xk_auth_token|8:YWRtaW4=|a33c36cf1c183ef0f232d1ea4a2921659e9ec900d0f6f1c395413bf80bf8bc01"'})
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/lib/python2.7/site-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/web.py", line 2721, in wrapper
        return method(self, *args, **kwargs)
      File "/root/DNSmasqWeb/xk_handler/xk_index.py", line 128, in get
        "cpu":self.get_cpu()
      File "/root/DNSmasqWeb/xk_handler/xk_index.py", line 111, in get_cpu
        return 100.0 - float(cpu)
    ValueError: invalid literal for float(): 95.0 id
[E 150831 02:55:51 web:1908] 500 GET /dashboard (192.168.8.134) 256.61ms
sh: /etc/init.d/dnsmasq: 没有那个文件或目录
[E 150831 02:55:52 web:1496] Uncaught exception GET /dashboard (192.168.8.134)
    HTTPServerRequest(protocol='http', host='192.168.8.88:9886', method='GET', uri='/dashboard', version='HTTP/1.1', remote_ip='192.168.8.134', headers={'Connection': 'keep-alive', 'Accept-Language': 'en,zh-CN;q=0.8,zh;q=0.6,ja;q=0.4,zh-TW;q=0.2,ko;q=0.2,de;q=0.2,ar;q=0.2,fr;q=0.2', 'Accept-Encoding': 'gzip, deflate, sdch', 'Cookie': '_xsrf=2|38998258|ad727c3bd08df0b3d1114f26e517925f|1440989744; xk_auth_token="2|1:0|10:1440989751|13:xk_auth_token|8:YWRtaW4=|a33c36cf1c183ef0f232d1ea4a2921659e9ec900d0f6f1c395413bf80bf8bc01"', 'Host': '192.168.8.88:9886', 'Accept': 'text/plain', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36'})
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/lib/python2.7/site-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/web.py", line 2721, in wrapper
        return method(self, *args, **kwargs)
      File "/root/DNSmasqWeb/xk_handler/xk_index.py", line 128, in get
        "cpu":self.get_cpu()
      File "/root/DNSmasqWeb/xk_handler/xk_index.py", line 111, in get_cpu
        return 100.0 - float(cpu)
    ValueError: invalid literal for float(): 95.0 id
[E 150831 02:55:52 web:1908] 500 GET /dashboard (192.168.8.134) 203.84ms
^CTraceback (most recent call last):
  File "run.py", line 10, in <module>
    main()
  File "/root/DNSmasqWeb/xk_application/xk_app.py", line 62, in main
    tornado.ioloop.IOLoop.instance().start()
  File "/usr/lib/python2.7/site-packages/tornado-4.2.1-py2.7-linux-x86_64.egg/tornado/ioloop.py", line 841, in start
    event_pairs = self._impl.poll(poll_timeout)
```

**Comment by h6w** [comment]
This actually looks like Issue #2 .  Can you please try my fork at https://github.com/h6w/DNSmasqWeb and see if that fixes the problem?
